{{- $prefix := printf "%v-" .Values.prefix | replace "<nil>-" "" -}}
{{- $suffix := printf "-%v" .Values.suffix | replace "-<nil>" "" -}}
{{- range $key, $val := .Values -}}
{{- $name := printf "%v%v%v" $prefix $key $suffix }}
{{- with $val -}}
{{- if ( and (ne $key "prefix") (ne $key "suffix") ) -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    release: {{ $name }}
  {{- if .serviceAnnotations }}
  annotations:
{{ toYaml .ingressAnnotations | indent 4 }}
  {{- end }}
spec:
  {{- if .revisionHistoryLimit }}
  revisionHistoryLimit: {{ .revisionHistoryLimit }}
  {{- else }}
  revisionHistoryLimit: 3
  {{- end }}
  {{- if .count }}
  replicas: {{ .count }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $name }}
      release: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        release: {{ $name }}
    spec:
      {{- if .restartPolicy }}
      restartPolicy: {{ .restartPolicy }}
      {{- end }}
      {{- if .pullSecret }}
      imagePullSecrets:
        - name: {{ .pullSecret }}
      {{- end }}
{{- if .securityContext }}
      securityContext:
{{ toYaml .securityContext | indent 8 }}
{{- end }}
      {{- if .initContainers }}
      initContainers:
{{ toYaml .initContainers | indent 6 }}
      {{- end }}
      containers:
        - name: {{ $name }}
          image: "{{ .image }}:{{ if .tag }}{{ .tag }}{{ else }}latest{{ end }}"
          {{- if .pullPolicy }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- else }}
          imagePullPolicy: Always
          {{- end }}
          {{- if .command }}
          command:
{{ toYaml .command | indent 12 }}
          {{- end -}}
          {{- if .args }}
          args:
{{ toYaml .args | indent 12 }}
          {{- end }}
          ports:
          {{- range .port -}}
          {{- $z := printf "%v" . }}
          {{- $v := splitList ":" $z }}
          {{- $length := len $v }}
          {{- if eq $length 2 }}
            - name: http-{{ index $v 1 }}
              containerPort: {{ index $v 1 }}
              protocol: TCP
          {{ else }}
            - name: http-{{ index $v 0 }}
              containerPort: {{ index $v 0 }}
              protocol: TCP
          {{ end }}
          {{- end -}}
          {{- if .env }}
          env:
          {{- range $envKey, $envVal := .env }}
            - name: {{ $envKey | quote }}
              value: {{ $envVal | quote }}
          {{- end }}
          {{- end }}
          {{- if .livenessProbe }}
          livenessProbe:
{{ toYaml .livenessProbe | indent 12 }}
          {{- end -}}
          {{- if .readinessProbe }}
          readinessProbe:
{{ toYaml .readinessProbe | indent 12 }}
          {{- end -}}
          {{- if .resources }}
          resources:
{{ toYaml .resources | indent 12 }}
          {{- end }}
          {{- if .volumes }}
          volumeMounts:
          {{- if .volumes.hostPath }}
          {{- range $volumeIndex, $volumeValue := .volumes.hostPath.path }}
          {{- $volumeSplit := splitList ":" $volumeValue }}
          {{- $length := len $volumeSplit }}
          - name: hostpath-{{ $volumeIndex }}
            mountPath: {{ index $volumeSplit 1 }}
            {{- if gt $length 2 }}
            subPath: {{ index $volumeSplit 2 }}
            {{- end }}
            {{- if gt $length 3 }}
            readOnly: {{ index $volumeSplit 3 }}
            {{- end }}
          {{- end }}
          {{- end }}

          {{- if .volumes.nfs }}
          {{- range $volumeIndex, $volumeValue := .volumes.nfs.path }}
          {{- $volumeSplit := splitList ":" $volumeValue }}
          {{- $length := len $volumeSplit }}
          - name: nfs-{{ $volumeIndex }}
            mountPath: {{ index $volumeSplit 1 }}
            {{- if gt $length 2 }}
            subPath: {{ index $volumeSplit 2 }}
            {{- end }}
            {{- if gt $length 3 }}
            readOnly: {{ index $volumeSplit 3 }}
            {{- end }}
          {{- end }}
          {{- end }}

          {{- if .volumes.pvc }}
          {{- range $volumeIndex, $volumeValue := .volumes.pvc.path }}
          {{- $volumeSplit := splitList ":" $volumeValue }}
          {{- $length := len $volumeSplit }}
          - name: pvc-{{ $volumeIndex }}
            mountPath: {{ index $volumeSplit 0 }}
            {{- if gt $length 1 }}
            subPath: {{ index $volumeSplit 1 }}
            {{- end }}
          {{- end }}
          {{- end }}

          {{- if .volumes.configMap }}
          {{- range $mapKey, $mapVal := .volumes.configMap }}
          {{- range $volumeIndex, $volumeValue := $mapVal.path }}
          {{- $volumeSplit := splitList ":" $volumeValue }}
          {{- $length := len $volumeSplit }}
          - name: {{ $mapKey }}
            mountPath: {{ index $volumeSplit 0 }}
            {{- if gt $length 1 }}
            subPath: {{ index $volumeSplit 1 }}
            {{- end }}
            {{- if gt $length 2 }}
            readOnly: {{ index $volumeSplit 2 }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}

          {{- if .volumes.secret }}
          {{- range $mapKey, $mapVal := .volumes.secret }}
          {{- range $volumeIndex, $volumeValue := $mapVal.path }}
          {{- $volumeSplit := splitList ":" $volumeValue }}
          {{- $length := len $volumeSplit }}
          - name: {{ $mapKey }}
            mountPath: {{ index $volumeSplit 0 }}
            {{- if gt $length 1 }}
            subPath: {{ index $volumeSplit 1 }}
            {{- end }}
            {{- if gt $length 2 }}
            readOnly: {{ index $volumeSplit 2 }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}

          {{- end }}
      {{- if .volumes }}
      volumes:
        {{- if .volumes.hostPath }}
        {{- range $volumeIndex, $volumeValue := .volumes.hostPath.path}}
        {{- $volumeSplit := splitList ":" $volumeValue }}
        - name: hostpath-{{ $volumeIndex }}
          hostPath:
            {{- if $val.volumes.hostPath.type }}
            type: {{ $val.volumes.hostPath.type }}
            {{ end }}
            path: {{ index $volumeSplit 0 }}
        {{- end }}
        {{- end }}

        {{- if .volumes.nfs }}
        {{- range $volumeIndex, $volumeValue := .volumes.nfs.path}}
        {{- $volumeSplit := splitList ":" $volumeValue }}
        - name: nfs-{{ $volumeIndex }}
          nfs:
            server: {{ $val.volumes.nfs.server }}
            path: {{ index $volumeSplit 0 }}
        {{- end }}
        {{- end }}

        {{- if .volumes.pvc }}
        {{- range $volumeIndex, $volumeValue := .volumes.pvc.path}}
        {{- $volumeSplit := splitList ":" $volumeValue }}
        - name: pvc-{{ $volumeIndex }}
          persistentVolumeClaim:
            claimName: {{ $val.volumes.pvc.name }}
        {{- end }}
        {{- end }}

        {{- if .volumes.configMap }}
        {{- range $mapKey, $mapVal := .volumes.configMap }}
        - name: {{ $mapKey }}
          configMap:
            name: {{ $mapKey }}
            {{- if $mapVal.items }}
            items:
            {{- range $volumeIndex, $volumeValue := $mapVal.items}}
            {{- $volumeSplit := splitList ":" $volumeValue }}
            - key: {{ index $volumeSplit 0 }}
              path: {{ index $volumeSplit 1 }}
            {{- end }}
            {{- end }}
        {{- end }}
        {{- end }}

        {{- if .volumes.secret }}
        {{- range $mapKey, $mapVal := .volumes.secret }}
        - name: {{ $mapKey }}
          configMap:
            name: {{ $mapKey }}
            {{- if $mapVal.items }}
            items:
            {{- range $volumeIndex, $volumeValue := $mapVal.items}}
            {{- $volumeSplit := splitList ":" $volumeValue }}
            - key: {{ index $volumeSplit 0 }}
              path: {{ index $volumeSplit 1 }}
            {{- end }}
            {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
---
{{- end -}}
{{- end -}}
{{- end -}}
