{{- $enable := dict "key" "" }}
{{- range $key, $val := .Values -}}
{{- with $val -}}
{{- if ( and (ne $key "prefix") (ne $key "suffix") ) -}}
{{- if .host -}}
{{$_ := set $enable "key" $key }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- $enable := pluck "key" $enable }}

{{- if index $enable 0 -}}
{{- $prefix2 := printf "%v-" .Values.prefix | replace "<nil>-" "" }}
{{- $prefix := printf "%v" .Values.prefix | replace "<nil>" "" }}
{{- $suffix := printf "-%v" .Values.suffix | replace "-<nil>" "" }}

{{- range $key, $val := .Values -}}
{{- with $val -}}
{{- if ( and (ne $key "prefix") (ne $key "suffix") ) -}}
{{- if .host -}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if $prefix }}
  name: {{ $prefix }}{{ $suffix }}
  labels:
    app: {{ $prefix }}{{ $suffix }}
    release: {{ $prefix }}{{ $suffix }}
{{- else }}
  name: {{ index $enable 0 }}{{ $suffix }}
  labels:
    app: {{ index $enable 0 }}{{ $suffix }}
    release: {{ index $enable 0 }}{{ $suffix }}
{{- end }}
  {{- if .serviceAnnotations }}
  annotations:
{{ toYaml .ingressAnnotations | indent 4 }}
  {{- end }}
spec:
  {{- if .tls }}
  tls:
  {{- range $key, $val := .tls }}
  - secretName: {{ $key }}
  {{- if $val }}
    hosts:
  {{- $domain := splitList ";" $val }}
  {{- range $domain }}
    - {{ . }}
  {{- end }}
  {{- end }}
  {{- end -}}
  {{- end }}
  rules:
{{- range $k, $val := .host}}
    {{- $domain := splitList ";" $val }}
    {{- range $domain }}
    - host: {{ . }}
      http:
        paths:
          - path:
            backend:
              serviceName: {{ printf "%v%v%v" $prefix2 $key $suffix }}
              servicePort: http-{{ $k }}
---
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
